homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('addMatkul', views.addMatkul, name='addMatkul'),
    path('delMatkul/<str:nama>', views.delMatkul, name='delMatkul'),
    path('viewMatkul/<str:nama>', views.viewMatkul, name='viewMatkul'),
]

matkul/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
# nama mata kuliah, dosen pengajar, jumlah sks, deskripsi mata kuliah, semester tahun(contoh: Gasal 2019/2020) dan ruang kelas
class mataKuliah(models.Model):
    
    nama = models.CharField(max_length = 50, help_text = "Enter The Name!")
    dosen = models.CharField(max_length = 50)
    sks = models.IntegerField()
    deskripsi = models.TextField()
    smtTahun = models.CharField(max_length = 50)
    kelas = models.CharField(max_length = 50)

    def __str__(self):
        return self.nama

class mataKuliahForm(ModelForm):
    class Meta:
        model = mataKuliah
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'smtTahun', 'kelas']

class tugasKuliah(models.Model):

    nama = models.CharField(max_length = 50)
    deadline = models.DateTimeField()
    mataKuliah = models.ForeignKey(
        'homepage.mataKuliah', on_delete=models.CASCADE
    )

    def __str__(self):
        return self.nama

homepage/views.py
from django.shortcuts import render, redirect
from .models import mataKuliah, mataKuliahForm, tugasKuliah
import datetime

# Create your views here.

def index(request):
    matKuls = mataKuliah.objects.all()

    return render(request, 'index.html', {'matKuls': matKuls})

def addMatkul(request):

    if request.method == 'POST':
        form = mataKuliahForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('homepage:index')
    else:
        form = mataKuliahForm()
    

    return render(request, 'addMatkul.html', {'form' : form})

def delMatkul(request, nama):
    matKuls = mataKuliah.objects.filter(nama = nama)

    matKuls.delete()

    return redirect('homepage:index')

def viewMatkul(request, nama):
    matKul = mataKuliah.objects.filter(nama = nama)
    tugas = tugasKuliah.objects.all().order_by('deadline')

    return render(request, 'viewMatkul.html', {'matKul' : matKul, 'tugas2' : tugas.order_by('deadline')})


    # Intended code for time
    # result = []
    # warning1, warning2, warning3 = False, False, False

    # timeSnow = datetime.datetime.now().timestamp()
    # timeSDead  = tugas.deadline.timestamp()

    # dateNow = datetime.datetime.fromtimestamp(timeSnow)
    # dateDead = datetime.datetime.fromtimestamp(timeSDead)

    # if (dateNow.month == dateDead.month):
    #     if (dateNow.day == dateDead.day):
    #         warning3 = True
    #     else:
    #         warning2 = True
    # else:
    #     warning1 = True

homepage/templates/addMatkul.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <h2 class="text-center">Add Mata Kuliah</h2>

    <form id="form" method="POST" action="#">
        {% csrf_token %}

        {{ form|crispy }}
        <br>

        <button type="submit" class="btn btn-outline-success btn-block">Add</button>
    </form>
{% endblock %}

homepage/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700&display=swap" rel="stylesheet">

  </head>

  <body>
      {% include 'includes/navbar.html' %}

      <div class="container d-flex align-items-center min-vh-100">

        <div class="table-responsive text-center">

          {% block body %}

          {% endblock %}

        </div>
      </div>

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <h2>Hello,</h2>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <!-- <li class="nav-item active">
          <a class="nav-link" href="{% url 'homepage:addMatkul' %}">Add MatKul</a>
        </li> -->
        <li class="nav-item disabled">
          <a class="nav-link" href="#">Admin</a>
        </li>
      </ul>
      <span class="navbar-text">
        Jeremy Victor
      </span>
    </div>
  </nav>

homepage/templates/index.html
{% extends 'base.html' %}

{% block body %}
<h1>JADWAL KULIAH</h1>

<div class="table-responsive">

    <table class="table table-hover" style="padding-left: 10px; padding-right: 10px;">
        <thead>
            <tr>
                <th scope="col">Nama MatKul</th>
                <th scope="col">Nama Dosen</th>
                <th scope="col">Jumlah SKS</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Semester Tahun</th>
                <th scope="col">Kelas</th>
            </tr>
        </thead>
        
        <tbody>
            {% for matKul in matKuls %}

                <tr class='clickable-row' data-url="{% url 'homepage:viewMatkul' matKul.nama %}">
                    <td>{{matKul.nama}}</td>
                    <td>{{matKul.dosen}}</td>
                    <td>{{matKul.sks}}</td>
                    <td>{{matKul.deskripsi|slice:":15"}}</td>
                    <td>{{matKul.smtTahun}}</td>
                    <td>{{matKul.kelas}}</td>

                </tr>
                
            {% endfor %}
        </tbody>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script>
            jQuery(document).ready(function($) {
                $(".clickable-row").click(function() {
                    window.location = $(this).data("url");
                    // console.log("BISA NIH");
                });
            });
        </script>

    </table>

    <!-- <table class="table table-borderless">
        <thead>
            <th scope="col">
                <form>
                    <button type="submit" class="btn btn-success" formaction="{% url 'homepage:addMatkul' %}">Add</button>
                </form>
            </th>

            <th scope="col">
                <form>
                    <button type="submit" class="btn btn-danger" formaction="{% url 'homepage:addMatkul' %}">Delete</button>
                </form>
            </th>
        </thead>
    </table> -->

    <form>
        <button type="submit" class="btn btn-outline-success btn-block" formaction="{% url 'homepage:addMatkul' %}">Add</button>
    </form>
    
</div>


{% endblock %}

homepage/templates/viewMatkul.html
{% extends 'base.html' %}

{% block body %}

    {% for info in matKul %}
    <h1>{{info.nama}}</h1>
        <div class="container-fluid table-responsive">
            <table class="table table-borderless">
                <thead>
                    <tr>
                        <th class="col-md-auto" scope="col"></th>
                        <th class="col-md-auto" scope="col"></th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <th scope="row">Dosen</th>
                        <td><p class="h4">{{info.dosen}}</p></td>
                    </tr>

                    <tr>
                        <th scope="row">Jumlah SKS</th>
                        <td><p class="h4">{{info.sks}}</p></td>
                    </tr>

                    <tr>
                        <th scope="row">Deskripsi</th>
                        <td><p class="lead">{{info.deskripsi}}</p></td>
                    </tr>

                    <tr>
                        <th scope="row">Semester Tahun</th>
                        <td><p class="h4">{{info.smtTahun}}</p></td>
                    </tr>

                    <tr>
                        <th scope="row">Kelas</th>
                        <td><p class="h4">{{info.kelas}}</p></td>
                    </tr>

                    <tr>
                        <th scope="row">Tugas</th>
                        <td>
                            <ul class="list-group">
                                {% for tugas in tugas2 %}
                                    <li class="list-group-item">{{tugas.nama}} : {{tugas.deadline}}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <form>
            <button type="submit" class="btn btn-outline-danger btn-block" formaction="{% url 'homepage:delMatkul' info.nama %}">Delete</button>
        </form>
    {% endfor %}
{% endblock %}